const $ = (s, p = document) => p.querySelector(s);
const $$ = (s, p = document) => [...p.querySelectorAll(s)];
const store = { recipes: 'naryori-recipes', theme: 'naryori-theme' };
const selections = { cuisine: '상관없음', mealType: '상관없음', dietary: ['제한 없음'], allergies: [] };
let activeRequest = 0, timeoutId, slowId, deletingId = null;

function setTheme(theme) { document.documentElement.dataset.theme = theme; localStorage.setItem(store.theme, theme); const dark = theme === 'dark'; $('#theme-toggle').setAttribute('aria-pressed', dark); $('#theme-toggle').setAttribute('aria-label', dark ? '라이트 모드로 전환' : '다크 모드로 전환'); }
setTheme(document.documentElement.dataset.theme || 'light');
$('#theme-toggle').addEventListener('click', () => setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));

$$('.chips:not(.selectable)').forEach(group => group.addEventListener('click', e => { const button = e.target.closest('.chip'); if (!button) return; $$('.chip', group).forEach(c => c.classList.remove('is-selected')); button.classList.add('is-selected'); selections[group.dataset.group] = button.dataset.value; }));
function tagListSelector(kind) { return kind === 'allergies' ? '#allergy-tags' : '#dietary-tags'; }
function renderTags(kind) { const node = $(tagListSelector(kind)); node.innerHTML = selections[kind].filter(v => v !== '제한 없음').map(v => `<span class="tag">${escapeHtml(v)}<button type="button" aria-label="${escapeHtml(v)} 삭제" data-remove="${escapeHtml(v)}">×</button></span>`).join(''); }
$$('.chips.selectable').forEach(group => group.addEventListener('click', e => { const button = e.target.closest('.chip'); if (!button) return; const kind = group.dataset.tags, value = button.dataset.value; if (kind === 'dietary' && value === '제한 없음') { selections.dietary = ['제한 없음']; $$('.chip', group).forEach(c => c.classList.toggle('is-selected', c === button)); renderTags(kind); return; } if (kind === 'dietary') { selections.dietary = selections.dietary.filter(v => v !== '제한 없음'); $('.chip[data-value="제한 없음"]', group).classList.remove('is-selected'); } const i = selections[kind].indexOf(value); if (i >= 0) selections[kind].splice(i, 1); else selections[kind].push(value); button.classList.toggle('is-selected'); if (kind === 'dietary' && !selections.dietary.length) { selections.dietary = ['제한 없음']; $('.chip[data-value="제한 없음"]', group).classList.add('is-selected'); } renderTags(kind); }));
['dietary', 'allergy'].forEach(inputKind => { const kind = inputKind === 'allergy' ? 'allergies' : 'dietary'; const input = $(`#${inputKind}-custom`); input.addEventListener('keydown', e => { if (e.key !== 'Enter') return; e.preventDefault(); const value = input.value.trim(); if (kind === 'dietary' && value) { selections.dietary = selections.dietary.filter(v => v !== '제한 없음'); $('.chips[data-tags="dietary"] .chip[data-value="제한 없음"]').classList.remove('is-selected'); } if (value && !selections[kind].includes(value)) selections[kind].push(value); input.value = ''; renderTags(kind); }); $(tagListSelector(kind)).addEventListener('click', e => { const value = e.target.dataset.remove; if (!value) return; selections[kind] = selections[kind].filter(v => v !== value); const chip = $(`.chips[data-tags="${kind}"] .chip[data-value="${CSS.escape(value)}"]`); if (chip) chip.classList.remove('is-selected'); if (kind === 'dietary' && !selections.dietary.length) { selections.dietary = ['제한 없음']; $('.chips[data-tags="dietary"] .chip[data-value="제한 없음"]').classList.add('is-selected'); } renderTags(kind); }); });

function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function getSaved() { try { return JSON.parse(localStorage.getItem(store.recipes) || '[]'); } catch { return []; } }
function setSaved(recipes) { localStorage.setItem(store.recipes, JSON.stringify(recipes)); renderSaved(); }
function recipeHtml(recipe) { const usage = recipe.ingredient_usage.map(x => `<li><b>${escapeHtml(x.ingredient)}</b>: ${escapeHtml(x.amount)}${x.remaining ? ` <span class="muted">(예상 잔량: ${escapeHtml(x.remaining)})</span>` : ''}</li>`).join(''); const additional = recipe.additional_ingredients.length ? recipe.additional_ingredients.map(x => `<li>${escapeHtml(x)}</li>`).join('') : '<li>없음</li>'; const steps = recipe.steps.map(x => `<li>${escapeHtml(x)}</li>`).join(''); return `<div class="notice">${escapeHtml(recipe.restriction_note)}</div><div class="meta"><span>⏱ ${escapeHtml(recipe.time)}</span><span>난이도 ${escapeHtml(recipe.difficulty)}</span><span>도구: ${escapeHtml(recipe.tools.join(', '))}</span></div><div class="card-section"><h4>핵심 재료 사용량</h4><ul>${usage}</ul></div><div class="card-section"><h4>추가로 필요한 재료 <small>(최대 2개)</small></h4><ul>${additional}</ul>${recipe.optional_garnish ? `<p class="optional-list">선택 재료: ${escapeHtml(recipe.optional_garnish)} (없어도 완성 가능)</p>` : ''}</div><div class="card-section"><h4>조리 순서</h4><ol class="steps-list">${steps}</ol></div><p class="safety-note">변질 의심 식재료는 사용하지 마세요. 알레르기 성분과 교차오염은 직접 확인해 주세요.</p>`; }
function renderResult(data) { const root = $('#result'); root.innerHTML = `<div class="result-summary"><b>AI가 인식한 필수 재료:</b> ${escapeHtml(data.recognized_ingredients.join(', '))}<br><small>${escapeHtml(data.overall_note)}</small></div><div class="recipe-grid"></div>`; const grid = $('.recipe-grid', root); const saved = getSaved(); data.recipes.forEach((recipe, index) => { const node = $('#recipe-template').content.cloneNode(true); const card = $('.recipe-card', node); $('.recipe-number', card).textContent = `추천 ${index + 1}`; $('.recipe-name', card).textContent = recipe.name; $('.recipe-reason', card).textContent = recipe.reason; $('.allergy-notice', card).textContent = recipe.restriction_note; $('.meta', card).innerHTML = `<span>⏱ ${escapeHtml(recipe.time)}</span><span>난이도 ${escapeHtml(recipe.difficulty)}</span><span>도구: ${escapeHtml(recipe.tools.join(', '))}</span>`; $('.usage-list', card).innerHTML = recipe.ingredient_usage.map(x => `<li><b>${escapeHtml(x.ingredient)}</b>: ${escapeHtml(x.amount)}${x.remaining ? ` <span class="muted">(예상 잔량: ${escapeHtml(x.remaining)})</span>` : ''}</li>`).join(''); $('.additional-list', card).innerHTML = recipe.additional_ingredients.length ? recipe.additional_ingredients.map(x => `<li>${escapeHtml(x)}</li>`).join('') : '<li>없음</li>'; $('.optional-list', card).textContent = recipe.optional_garnish ? `선택 재료: ${recipe.optional_garnish} (없어도 완성 가능)` : ''; const steps = $('.steps-list', card); recipe.steps.forEach(s => { const li = document.createElement('li'); li.textContent = s; steps.append(li); }); const id = recipe.id || `${Date.now()}-${index}`; recipe.id = id; const button = $('.save-button', card), wasSaved = saved.some(x => x.id === id); if (wasSaved) { button.textContent = '♥ 저장됨'; button.classList.add('saved'); } button.addEventListener('click', () => { const all = getSaved(); if (all.some(x => x.id === id)) return; setSaved([{...recipe, savedAt: new Date().toISOString()}, ...all]); button.textContent = '♥ 저장됨'; button.classList.add('saved'); }); grid.append(card); }); }
function renderRawResult(data) { const root = $('#result'), id = `raw-${Date.now()}`; root.innerHTML = `<div class="result-summary"><b>AI가 인식한 필수 재료:</b> ${escapeHtml(data.recognized_ingredients.join(', '))}<br><small>${escapeHtml(data.overall_note)}</small></div><article class="recipe-card"><div class="card-top"><span class="badge">AI 추천 결과</span><button class="save-button" type="button">♡ 전체 저장</button></div><h3 class="recipe-name">오늘의 냉장고 레시피</h3><div class="raw-text"></div><p class="safety-note">변질 의심 식재료는 사용하지 마세요. 알레르기 성분과 교차오염은 직접 확인해 주세요.</p></article>`; const card = $('.recipe-card', root); $('.raw-text', card).textContent = data.raw_text; $('.save-button', card).addEventListener('click', e => { setSaved([{ id, name: '오늘의 냉장고 레시피', reason: 'AI가 제안한 레시피 결과', time: 'AI 안내 참고', difficulty: 'AI 안내 참고', restriction_note: '성분표와 교차오염을 직접 확인하세요.', ingredient_usage: data.recognized_ingredients.map(ingredient => ({ingredient, amount:'AI 안내 참고', remaining:'수량 미입력'})), additional_ingredients: [], optional_garnish: '', tools: [], steps: data.raw_text.split('\n').filter(Boolean), savedAt: new Date().toISOString() }, ...getSaved()]); e.currentTarget.textContent = '♥ 저장됨'; e.currentTarget.classList.add('saved'); }); }
const renderStructuredResult = renderResult;
renderResult = function(data) { if (data.status === 'raw') return renderRawResult(data); return renderStructuredResult(data); };
function renderSaved() { const root = $('#saved-list'), recipes = getSaved(); if (!recipes.length) { root.innerHTML = '<div class="empty-state">아직 저장한 레시피가 없어요.<br>마음에 드는 레시피의 저장 버튼을 눌러 보세요.</div>'; return; } root.innerHTML = recipes.map(r => `<article class="saved-card" data-id="${escapeHtml(r.id)}"><div class="saved-summary"><div><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.ingredient_usage.map(x=>x.ingredient).join(', '))} · ${escapeHtml(r.time)} · 난이도 ${escapeHtml(r.difficulty)}</p><p>⚠ ${escapeHtml(r.restriction_note)}</p><p>저장일 ${new Date(r.savedAt).toLocaleDateString('ko-KR')}</p></div><div class="saved-actions"><button class="expand-button" type="button" aria-expanded="false">상세 보기</button><button class="delete-small" type="button" aria-label="${escapeHtml(r.name)} 삭제">삭제</button></div></div><div class="saved-detail" hidden>${recipeHtml(r)}</div></article>`).join(''); $$('.saved-card', root).forEach(card => { $('.expand-button', card).addEventListener('click', e => { const detail = $('.saved-detail', card), expanded = !detail.hidden; detail.hidden = expanded; e.currentTarget.textContent = expanded ? '상세 보기' : '접기'; e.currentTarget.setAttribute('aria-expanded', String(!expanded)); }); $('.delete-small', card).addEventListener('click', () => { deletingId = card.dataset.id; $('#delete-dialog').showModal(); }); }); }
$('#cancel-delete').addEventListener('click', () => $('#delete-dialog').close()); $('#confirm-delete').addEventListener('click', () => { setSaved(getSaved().filter(x => x.id !== deletingId)); $('#delete-dialog').close(); deletingId = null; });

function showMessage(message) { $('#form-message').textContent = message; }
function stopLoading() { clearTimeout(timeoutId); clearTimeout(slowId); $('#loading').hidden = true; $('.submit-button').disabled = false; }
$('#recipe-form').addEventListener('submit', async e => { e.preventDefault(); const ingredients = $('#ingredients').value.trim(), servings = $('#servings').value; if (!ingredients || !servings) { showMessage('꼭 쓰고 싶은 재료와 인원수를 입력해 주세요.'); return; } showMessage(''); const requestId = ++activeRequest, button = $('.submit-button'); button.disabled = true; $('#loading').hidden = false; $('#loading-detail').textContent = '조금만 기다려 주세요.'; $('#result').innerHTML = ''; slowId = setTimeout(() => { if (requestId === activeRequest) $('#loading-detail').textContent = '추천을 만들고 있어요. 조금만 더 기다려 주세요.'; }, 8000); try { const response = await fetch('/api/recommend', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ingredients, servings, cuisine:selections.cuisine, meal_type:selections.mealType, dietary:selections.dietary, allergies:selections.allergies}) }); if (requestId !== activeRequest) return; let data; try { data = await response.json(); } catch { throw new Error('AI 추천 서버가 예상하지 못한 응답을 보냈어요. 잠시 후 다시 시도해 주세요.'); } if (!response.ok) throw new Error(data.message || '서버에서 추천을 만들지 못했어요.'); if (data.status === 'conflict' || data.status === 'invalid') { showMessage(data.message); return; } renderResult(data); $('#result').scrollIntoView({behavior:'smooth', block:'start'}); } catch (err) { if (requestId !== activeRequest) return; if (!navigator.onLine) showMessage('인터넷 연결을 확인한 뒤 다시 시도해 주세요.'); else showMessage(err.message || 'AI 추천 중 오류가 발생했어요. 잠시 후 다시 시도해 주세요.'); } finally { if (requestId === activeRequest) stopLoading(); } });
renderSaved();
